name: Code quality checks
on: [push]
jobs:
  Code-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Checking code quality of repository ${{ github.repository }}."

      - name: 'Upload coverage to Codecov'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        #          directory: ./coverage/reports/
        #          env_vars: OS,PYTHON
        #          fail_ci_if_error: true
        #          files: ./coverage1.xml,./coverage2.xml
        #          flags: unittests
        #          name: codecov-umbrella
        #          path_to_write_report: ./coverage/codecov_report.txt
