name: hello-maven-release
on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  build-jar-job:
    name: 'Build JAR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
  - name: 'Setup Java 17'
      uses: actions/setup-java@v1
      with:
        java-version: 17
  - name: 'Build JAR'
      run: |
        ./mvnw clean package -DskipTests

  - name: 'Publish JAR'
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'hello-maven-release'
        path: target/hello-maven-release.jar
#        target-directory: '{{ github.workflow.event.workflow_job.job }}'

  - name: 'Create Release'
    if: contains(github.ref, 'v')
    id: create_release
    uses: actions/create-release@v1
    env:
      GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
    with:
      tag_name: ${{github.ref}}
      release_name: Release ${{github.ref}}
      body: |
        Initial release
      draft: false
      prerelease: false

  - name: 'Upload Release Asset'
    if: contains(github.ref, 'v')
    id: upload-release-asset
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
    with:
      upload_url: ${{steps.create_release.outputs.upload_url}}
      asset_path: target/hello-maven-release.jar
      asset_name: hello-maven.jar
      asset_content_type: application/java-archive

  - name: 'Write Upload URL To File'
    if: contains(github.ref, 'v')
    run: |
      echo "${{steps.create_release.outputs.upload_url}}" > upload_url.txt

  - name: 'Publish Upload URL'
    if: contains(github.ref, 'v')
    uses: actions/upload-artifact@v2-preview
    with:
      name: 'upload_url.txt'
      path: 'upload_url.txt'

#  - name: Release
#      uses: qcastel/github-actions-maven-release@master
#      with:
#        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#        maven-release-version-number: ${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.0
#        # version-minor: true
#        git-release-bot-name: "release-bot"
#        git-release-bot-email: "release-bot@rrajesh1979.com"

