name: hello-maven-native
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
jobs:
  build-non-windows-image:
    name: 'Build Non-Windows Image'
    needs: [ build-jar-job ]
    strategy:
      matrix:
        os: [ 'macos-latest' ] #'ubuntu-latest',
        gu-binary: [ gu ]
        include:
#          - os: 'ubuntu-latest'
#            gu-binary: gu
#            label: 'linux'
          - os: 'macos-latest'
            gu-binary: gu
            label: 'mac'
    runs-on: ${{matrix.os}}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 17'
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'maven'

      - name: 'Set up Graal'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.0'
          java: 'java17'

      - name: 'Install native-image component'
        run: |
          ${{ matrix.gu-binary }} install native-image

      - name: 'Cache Maven packages'
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 'Download asset'
        uses: actions/download-artifact@v2
        with:
          name: hello-maven-release

      - run: |
          ls -a
          tree -L 3

      - name: 'Build Native Image'
        run: |
          ./mvnw -B --file pom.xml -Pnative package
#            native-image \
#            --no-server \
#            --no-fallback \
#            # -H:ReflectionConfigurationResources=reflection-config.json \
#            # -H:IncludeResources=logback.xml \
#            --allow-incomplete-classpath \
#            -jar hello-maven-1.0-SNAPSHOT.jar

      - name: 'Publish Native Image'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'hello-maven-${{matrix.label}}'
          path: 'hello-maven-all'

      - run: |
          ls -a