name: hello-maven-release
on:
  push:
    tags:
      - "v*"
    branches:
      - 'master'
jobs:
  build-jar-job:
    name: 'Build JAR'
    runs-on: ubuntu-latest
    env:
      working-dir: ./hello-maven-build-dir
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 17'
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: 'maven'

      - name: 'Build JAR'
        run: |
          ./mvnw clean package -DskipTests

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'hello-maven-release'
          path: /home/runner/work/hello-maven/hello-maven/target/hello-maven*.jar

      - name: 'Download asset'
        uses: actions/download-artifact@v2
        with:
          name: hello-maven-release

      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
